import { lazy, Suspense } from "react";
import { Navigate, Route, Routes, useLocation } from "react-router-dom";
import { Notice, RouteSheet } from "../components/ui";
import { AppLayout } from "../layouts/AppLayout";

const load = <T,>(factory: () => Promise<T>, key: keyof T) => lazy(() => factory().then((m) => ({ default: m[key] as React.ComponentType })));
const InicioPage=load(()=>import("../features/reportes/InicioPage"),"InicioPage"), VentasPage=load(()=>import("../features/ventas/VentasPage"),"VentasPage"), NuevaVentaPage=load(()=>import("../features/ventas/NuevaVentaPage"),"NuevaVentaPage"), VentaDetallePage=load(()=>import("../features/ventas/VentaDetallePage"),"VentaDetallePage");
const ProductosPage=load(()=>import("../features/productos/ProductosPage"),"ProductosPage"), ProductoFormPage=load(()=>import("../features/productos/ProductoFormPage"),"ProductoFormPage"), ProductoDetallePage=load(()=>import("../features/productos/ProductoDetallePage"),"ProductoDetallePage"), CategoriasPage=load(()=>import("../features/productos/CategoriasPage"),"CategoriasPage");
const MovimientosPage=load(()=>import("../features/movimientos/MovimientosPage"),"MovimientosPage"), NuevoMovimientoPage=load(()=>import("../features/movimientos/NuevoMovimientoPage"),"NuevoMovimientoPage"), MovimientoDetallePage=load(()=>import("../features/movimientos/MovimientoDetallePage"),"MovimientoDetallePage"), MasPage=load(()=>import("../features/mas/MasPage"),"MasPage");
const ReportesPage=load(()=>import("../features/reportes/ReportesPage"),"ReportesPage"), PdfMensualPage=load(()=>import("../features/reportes/PdfMensualPage"),"PdfMensualPage"), ProyeccionesPage=load(()=>import("../features/proyecciones/ProyeccionesPage"),"ProyeccionesPage");
const ConfiguracionPage=load(()=>import("../features/configuracion/ConfiguracionPage"),"ConfiguracionPage"), ModoConfiguracionPage=load(()=>import("../features/configuracion/ModoConfiguracionPage"),"ModoConfiguracionPage"), RespaldosPage=load(()=>import("../features/configuracion/RespaldosPage"),"RespaldosPage"), ExportacionesPage=load(()=>import("../features/configuracion/ExportacionesPage"),"ExportacionesPage");
function Cargando(){return <Notice>Cargando pantalla...</Notice>}
function Rutas(){return <Route element={<AppLayout/>}><Route index element={<InicioPage/>}/><Route path="ventas" element={<VentasPage/>}/><Route path="ventas/nueva" element={<NuevaVentaPage/>}/><Route path="ventas/:ventaId" element={<VentaDetallePage/>}/><Route path="productos" element={<ProductosPage/>}/><Route path="productos/nuevo" element={<ProductoFormPage/>}/><Route path="productos/categorias" element={<CategoriasPage/>}/><Route path="productos/:productoId" element={<ProductoDetallePage/>}/><Route path="productos/:productoId/editar" element={<ProductoFormPage/>}/><Route path="movimientos" element={<MovimientosPage/>}/><Route path="movimientos/nuevo" element={<NuevoMovimientoPage/>}/><Route path="movimientos/:movimientoId" element={<MovimientoDetallePage/>}/><Route path="mas" element={<MasPage/>}/><Route path="reportes" element={<ReportesPage/>}/><Route path="reportes/pdf-mensual" element={<PdfMensualPage/>}/><Route path="proyecciones" element={<ProyeccionesPage/>}/><Route path="configuracion" element={<ConfiguracionPage/>}/><Route path="configuracion/modo" element={<ModoConfiguracionPage/>}/><Route path="configuracion/respaldos" element={<RespaldosPage/>}/><Route path="configuracion/exportaciones" element={<ExportacionesPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route>}
export function AppRouter(){const location=useLocation();const background=(location.state as {backgroundLocation?:Location}|null)?.backgroundLocation;return <Suspense fallback={<div className="mx-auto max-w-md px-4 pt-5"><Cargando/></div>}><Routes location={background??location}><Rutas/></Routes>{background&&<Routes><Route path="ventas/:ventaId" element={<RouteSheet label="Detalle de venta"><VentaDetallePage/></RouteSheet>}/><Route path="productos/:productoId" element={<RouteSheet label="Detalle del producto"><ProductoDetallePage/></RouteSheet>}/><Route path="movimientos/:movimientoId" element={<RouteSheet label="Detalle del movimiento"><MovimientoDetallePage/></RouteSheet>}/></Routes>}</Suspense>}
