import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function rows(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('mora-v2:local-workspace:v1:this-browser');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});try{const names=[...db.objectStoreNames],tx=db.transaction(names);return Object.fromEntries(await Promise.all(names.map(async n=>[n,await new Promise<any[]>((ok,no)=>{const r=tx.objectStore(n).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);})])));}finally{db.close();}});}
async function enter(page:Page){await page.getByRole('button',{name:'Inicio',exact:true}).click();await page.getByRole('button',{name:'Movimientos',exact:true}).click();await expect(page.getByRole('heading',{name:'Movimientos',exact:true})).toBeVisible();}
async function addProduct(page:Page){await page.getByRole('button',{name:'Productos',exact:true}).click();await page.getByRole('button',{name:'Agregar producto',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Conteo QA');await page.getByLabel('Precio $',{exact:true}).fill('3500');await page.getByRole('button',{name:'Guardar producto',exact:true}).click();await page.getByRole('button',{name:'Cerrar confirmación',exact:true}).click();await page.getByRole('button',{name:'Registrar compra',exact:true}).click();await page.getByLabel('Unidades individuales').fill('6');await page.getByLabel('Costo total de estas unidades $').fill('125000');await page.getByLabel('Recibí estas unidades y pagué este total en efectivo').check();await page.getByRole('button',{name:'Guardar recepción y pago',exact:true}).click();await page.getByRole('button',{name:'Cerrar confirmación',exact:true}).click();}
async function money(page:Page,kind:'gasto'|'aporte',amount:string,concept:string){await page.getByRole('button',{name:`Registrar ${kind}`,exact:true}).click();await page.getByLabel('Importe $',{exact:true}).fill(amount);await page.getByLabel('Concepto / procedencia').fill(concept);await page.getByLabel('Nota (opcional)').fill('QA aislado');await page.getByLabel('Comprobé el movimiento de efectivo').check();await page.getByRole('button',{name:`Guardar ${kind}`,exact:true}).click();await page.getByRole('button',{name:'Cerrar confirmación',exact:true}).click();}
async function count(page:Page,q:string){await page.getByRole('button',{name:'Contar y ajustar stock',exact:true}).click();await page.getByLabel('Cantidad contada').fill(q);await page.getByLabel('Motivo',{exact:true}).fill('Conteo de estante');await page.getByLabel('Comprobé el conteo y autorizo este ajuste').check();await page.getByRole('button',{name:'Guardar conteo y ajuste',exact:true}).click();await page.getByRole('button',{name:'Cerrar confirmación',exact:true}).click();}
test('real mobile movements persist offline, exact FIFO and JSON restores in a separate profile',async({page,context,browser})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('./');await expect(page).toHaveTitle(/Mora/);await addProduct(page);await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await enter(page);
 await money(page,'gasto','1000','Bolsas');await money(page,'aporte','5000','Aporte externo QA');await count(page,'3');let data=await rows(page);expect(data.stockCounts[0]).toMatchObject({before:6,counted:3,delta:-3,cost:{numerator:'62500',denominator:'1'}});expect(data.movements).toHaveLength(2);
 await count(page,'5');await page.reload();await enter(page);await expect(page.getByText('Sin conexión · guardado en este equipo · Sin sincronización',{exact:true})).toBeVisible();
 for(const width of [360,390,430,1280]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/mora-movements-mobile.png',fullPage:false});
 await page.locator('.m2-operation-history').filter({hasText:'Bolsas'}).locator('summary').click();await expect(page.locator('.m2-operation-history').filter({hasText:'Bolsas'}).getByText('QA aislado',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Productos',exact:true}).click();await expect(page.locator('.m2-stockpill')).toHaveText('5 un.');await page.getByRole('button',{name:'Inicio',exact:true}).click();await page.getByRole('button',{name:'Backup y restauración',exact:true}).click();await page.getByRole('button',{name:'Preparar respaldo',exact:true}).click();const wait=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar JSON'}).click();const file=await wait;const buffer=await readFile((await file.path())!);const backup=JSON.parse(buffer.toString());expect(backup.formatVersion).toBe(2);expect(backup.data.stockCounts).toHaveLength(2);
 const target=await browser.newContext({baseURL:test.info().project.use.baseURL,viewport:{width:390,height:844}});try{const receiver=await target.newPage();await receiver.goto('./');await receiver.getByRole('button',{name:'Backup y restauración',exact:true}).click();await receiver.getByLabel('Elegir respaldo JSON').setInputFiles({name:'movements.json',mimeType:'application/json',buffer});await receiver.getByLabel('Confirmo recuperar este respaldo en este espacio vacío.').check();await receiver.getByRole('button',{name:'Restaurar respaldo',exact:true}).click();await expect(receiver.getByRole('status').filter({hasText:'Datos recuperados'})).toBeVisible();data=await rows(receiver);for(const n of Object.keys(backup.data))if(n!=='metadata')expect(data[n]).toEqual(backup.data[n]);await receiver.reload();await enter(receiver);await expect(receiver.locator('.m2-operation-history').filter({hasText:'Bolsas'})).toBeVisible();}finally{await target.close();}
 expect(errors).toEqual([]);
});
test('native storage error preserves durable form across reload, retry and double touch apply once',async({page})=>{
 await page.goto('./');await enter(page);await page.getByRole('button',{name:'Registrar gasto',exact:true}).click();await page.getByLabel('Importe $',{exact:true}).fill('1234');await page.getByLabel('Concepto / procedencia').fill('Limpieza');await page.getByLabel('Comprobé el movimiento de efectivo').check();
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args:Parameters<IDBObjectStore['add']>){if(this.name==='movements'){IDBObjectStore.prototype.add=original;throw new DOMException('QA full','QuotaExceededError');}return original.apply(this,args);};});
 await page.getByRole('button',{name:'Guardar gasto',exact:true}).click();await expect(page.getByRole('alert')).toContainText('No queda espacio');let data=await rows(page);expect(data.cashEntries).toHaveLength(0);expect(data.movements).toHaveLength(0);const command=data.writeIntents[0].command;
 await page.reload();await expect(page.getByRole('heading',{name:'Movimiento pendiente de confirmar'})).toBeVisible();await page.getByRole('button',{name:'Reintentar confirmación',exact:true}).dblclick();await expect(page.getByRole('button',{name:'Cerrar confirmación',exact:true})).toBeVisible();data=await rows(page);expect(data.movements).toHaveLength(1);expect(data.commands[0]).toMatchObject({id:command.id,registeredAt:command.registeredAt});await page.reload();await expect(page.getByRole('heading',{name:'Movimiento confirmado'})).toBeVisible();expect((await rows(page)).cashEntries).toHaveLength(1);
});
